# Pipeline Global Config - Optimization model
pipeline:
  image_size: 2048                          # resolution of output images
  output_dir: "/data/output/New_Test"       # output folder for processed files
  quality: "medium"                           # define decimation quality preset: high, medium and low
  verbose: 1

models:
  - path: "/data/input/obj/sito_archeologico.obj"
