# Pipeline Global Config - Optimization model
pipeline:
  image_size: 2048                          # resolution of output images
  output_dir: "/data/output/New_Test"       # output folder for processed files
  quality: "high"                           # define decimation quality preset: high, medium and low
  verbose: 0


models:
  # - path: "/data/input/glb/Surdulica.glb"
  - path: "/data/input/glb/building.glb"
