# Pipeline Global Config - Optimization model
pipeline:
  remesh: false                       # enable/disable remeshing
  decimate: true                      # enable/disable decimation
  decimate_ratio: 0.5                 # decimation ratio (if enabled)
  output_format: "glb"                # final export format: obj, gltf, glb, fbx, usd, ply
  improve_material: true              # generate Ambient Occlusion and Roughness maps
  image_resolution: 1024              # resolution of output images
  output_folder: "/root/output"       # output folder for processed files

models:
  - path: "/root/input/1beb8eed06eecfe6af6b2b33e6ac8085.glb"
    name: "1beb8eed06eecfe6af6b2b33e6ac8085"
    # basecolor_img: "/root/input_tmp/texture_CM002.jpg"
