# Pipeline Global Config
pipeline:
  remesh: true                        # enable/disable remeshing
  decimate: false                     # enable/disable decimation
  decimate_ratio: 0.5                 # decimation ratio (if enabled)
  output_format: "usd"                # final export format: obj, gltf, glb, fbx, usd, ply
  improve_material: true              # generate Ambient Occlusion and Roughness maps
  image_resolution: 1024              # resolution of output images
  output_folder: "/data/output"       # output folder for processed files

models:
  - path: "/data/input_tmp/hat.obj"
    name: "Hat"
    basecolor_img: "/data/input_tmp/texture_CM002.jpg"  # path to basecolor image (optional)
  - path: "/data/input_tmp/monkey.obj"
    name: "Monkey"
    # no basecolor image specified
